Repository Sxvxgee/DankCord, pull requests merged in 2022-12, with the labels that each got.

#1 PR: Bugfixes & A Message Object
  setup.py
  src/DankCord/DankCord.py
  src/DankCord/Objects.py
  src/DankCord/__init__.py
  src/DankCord/ws.py
Labels: enhancement

#2 New objects, bug fixes, code changes
  Changelog.md
  src/DankCord/DankCord.py
  src/DankCord/Objects.py
  src/DankCord/__init__.py
Labels: enhancement

#6 Temporary
  src/DankCord/DankCord.py
  src/DankCord/Objects.py
  src/DankCord/logger.py
  src/DankCord/ws.py
Labels: enhancement

#8 Refactor
  .gitignore
  Changelog.md
  example.py
  src/DankCord/DankCord.py
  src/DankCord/DankMemer.py
  src/DankCord/Objects.py
  src/DankCord/__init__.py
  src/DankCord/exceptions.py
  src/DankCord/gateway.py
  src/DankCord/logger.py
  src/DankCord/ws.py
Labels: enhancement, bug fix, refactor, Review Required

#13 PR: Bugfixes & Button Clicking & Other New Functions
  .gitignore
  src/DankCord/DankCord.py
  src/DankCord/Objects.py
  src/DankCord/exceptions.py
  src/DankCord/gateway.py
Labels: enhancement, bug fix, Review Required

#17 Major refactor
  .gitignore
  example.py
  pyproject.toml
  requirements.txt
  setup.py
  src/DankCord/DankCord.py
  src/DankCord/DankMemer.py
  src/DankCord/Objects.py
  src/DankCord/__init__.py
  src/DankCord/exceptions.py
  src/DankCord/gateway.py
  src/DankCord/logger.py
Labels: enhancement, refactor, Review Required

#19 Temporarybranch
  src/DankCord/DankCord.py
  src/DankCord/Objects.py
  src/DankCord/core.py
  src/DankCord/exceptions.py
  src/DankCord/gateway.py
Labels: enhancement, bug fix, Review Required

#21 Development: v0.0.3
  .gitignore
  Changelog.md
  README.md
  example.py
  pyproject.toml
  requirements.txt
  setup.py
  src/DankCord/DankCord.py
  src/DankCord/DankMemer.py
  src/DankCord/Objects.py
  src/DankCord/__init__.py
  src/DankCord/core.py
  src/DankCord/exceptions.py
  src/DankCord/gateway.py
  src/DankCord/logger.py
  src/DankCord/ws.py
Labels: enhancement, help wanted, refactor, Review Required, Milestone
